source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'ReactiveKiwi_Example', :exclusive => true do
  pod 'ReactiveKiwi', :path => '../'
end

target 'ReactiveKiwi_Tests' , :exclusive => true do
  pod 'ReactiveKiwi', :path => '../'
  pod 'Kiwi'
end

